image: continuumio/miniconda:latest
variables:
  # JEKYLL_ENV: production
  # LC_ALL: C.UTF-8
  TEST_ENV_NAME: test-env

before_script:
  - conda update -y -c conda-forge -c defaults conda
  - conda init bash
  - source /root/.bashrc
  - conda env create -n ${TEST_ENV_NAME} --file environment.yml
  - conda install -c conda-forge -c defaults -n ${TEST_ENV_NAME} jupyter
  - conda activate ${TEST_ENV_NAME}
  - conda list
  - which python


test:
  stage: test
  script:
    - which python
    - conda list
    - echo ${PATH}
    - jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute image-analysis-session/*.ipynb
